#define CTRL_A           0x01
#define CTRL_D           0x04
#define CTRL_I           0x09
#define CTRL_J           0x0A
#define CTRL_Q           0x11
#define CTRL_S           0x13
#define KEY_ESC          0x1B
#define HOR_TAB          CTRL_I
#define LINE_FEED        CTRL_J
#define EXIT_MODE        1
#define CONTINUE_MODE    0
#define FILE_WRITTEN     0
#define FILE_NOT_WRITTEN 1